services:
  app:
    image: 235969061926.dkr.ecr.ap-northeast-2.amazonaws.com/billie-app:latest
    container_name: billie-spring-app
    network_mode: host
    env_file:
      - .env
    restart: always
    volumes:
      - ./heapdumps:/heapdumps
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xms2g -Xmx3g
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+PrintFlagsFinal
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/heapdumps
