services:
  app:
    image: 235969061926.dkr.ecr.ap-northeast-2.amazonaws.com/billie-app:latest
    container_name: billie-spring-app
    network_mode: host
    env_file:
      - .env
    restart: always