#!/bin/bash
cd /home/ubuntu/app

cat > .env << EOF
SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
SPRING_ELASTICSEARCH_URIS=${SPRING_ELASTICSEARCH_URIS}
EOF

docker pull choijake/billie-app:latest
docker-compose up -d